default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
  pool: 5

development:
  <<: *default
  database: events_development

test:
  <<: *default
  database: events_test

production:
  <<: *default
  database: events_production
  # username: events
  password: <%= ENV['EVENTS_DATABASE_PASSWORD'] %>
