# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5e186d0af7eac75d94c9992ee4305572dfe6c75fef2b33cbb86b52e2636ccbe217f41d37bc1f7930de770383631d4e0d0160d10507da5ff490d97ccf2218dea

test:
  secret_key_base: 108a2d7850c01d717e4eebafb2a8bd00f5c81a6b01b836ac9c2270e16624c15cd53fcff80fe8347127d21e74909cfed5ca4c59552f8936dc93efc99ab38556aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
